name: bondedapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/user1.png
    - assets/images/user2.png
    - assets/images/bonded_logo.png

    # Bondie icons
    - assets/images/bondie_icons/bondie_depressed.png
    - assets/images/bondie_icons/bondie_ghost.png
    - assets/images/bondie_icons/bondie_happy.png
    - assets/images/bondie_icons/bondie_sad.png
    - assets/images/bondie_icons/bondie_super_happy.png
    - assets/images/bondie_icons/bondie_talking.png

    # Bondie Skins
    - assets/images/bondie_skins/bondie_cook.png
    - assets/images/bondie_skins/bondie_cop.png
    - assets/images/bondie_skins/bondie_doctor.png
    - assets/images/bondie_skins/bondie_firefighter.png
    - assets/images/bondie_skins/bondie_nerd.png
    - assets/images/bondie_skins/bondie_pirate.png
    - assets/images/bondie_skins/bondie_santa.png
    - assets/images/bondie_skins/bondie_soccer.png
    - assets/images/bondie_skins/bondie_thief.png

    # Recommendations
    - assets/images/recommendations/zero_latency_logo.webp
    - assets/images/recommendations/game_over_logo.png
    - assets/images/recommendations/gulbenkian_garden.jpg
    - assets/images/recommendations/lisbon_christmas_lights.jpg
    - assets/images/recommendations/omakase_wa.jpeg
    - assets/images/recommendations/tile_museum.jpg

