name: bondedapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fl_chart: ^0.69.0
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.14.0
  confetti: ^0.7.0
  path_provider: ^2.0.15


flutter:
  uses-material-design: true

  assets:
    - assets/images/user1.png
    - assets/images/user2.png
    - assets/images/bonded_logo.png
    - assets/images/couple_album.jpg
    - assets/images/couple_selfie.png

    # Bondie icons
    - assets/images/bondie_icons/bondie_depressed.png
    - assets/images/bondie_icons/bondie_ghost.png
    - assets/images/bondie_icons/bondie_happy.png
    - assets/images/bondie_icons/bondie_sad.png
    - assets/images/bondie_icons/bondie_super_happy.png
    - assets/images/bondie_icons/bondie_talking.png

    # Bondie Skins
    - assets/images/bondie_skins/bondie_cook.png
    - assets/images/bondie_skins/bondie_cop.png
    - assets/images/bondie_skins/bondie_doctor.png
    - assets/images/bondie_skins/bondie_firefighter.png
    - assets/images/bondie_skins/bondie_nerd.png
    - assets/images/bondie_skins/bondie_pirate.png
    - assets/images/bondie_skins/bondie_santa.png
    - assets/images/bondie_skins/bondie_soccer.png
    - assets/images/bondie_skins/bondie_thief.png

    # Bondie Time Capsule
    - assets/images/bondie_time_capsule/time_capsule_closed.png
    - assets/images/bondie_time_capsule/time_capsule_opened.png
    - assets/images/bondie_time_capsule/time_capsule_submission.png

    # Recommendations
    - assets/images/recommendations/real_world_dates/zero_latency_logo.webp
    - assets/images/recommendations/real_world_dates/game_over_logo.png
    - assets/images/recommendations/real_world_dates/gulbenkian_garden.jpg
    - assets/images/recommendations/real_world_dates/lisbon_christmas_lights.jpg
    - assets/images/recommendations/real_world_dates/omakase_wa.jpeg
    - assets/images/recommendations/real_world_dates/tile_museum.jpg

    # Bruno Submissions
    - assets/images/submissions/bruno/bruno_submission_1.png
    - assets/images/submissions/bruno/bruno_submission_2.png
    - assets/images/submissions/bruno/bruno_submission_3.png
    - assets/images/submissions/bruno/bruno_submission_4.png
    - assets/images/submissions/bruno/bruno_submission_5.png

    #Ana Submissions
    - assets/images/submissions/ana/ana_submission_1.png
    - assets/images/submissions/ana/ana_submission_2.png
    - assets/images/submissions/ana/ana_submission_3.png
    - assets/images/submissions/ana/ana_submission_4.png
    - assets/images/submissions/ana/ana_submission_5.png


